# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "forwarded_port", guest: 3000, host: 3000

  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

  config.vm.synced_folder "../hello", "/hello"

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = ["cookbooks"]
    chef.roles_path = "roles"

    chef.add_role "base"
    chef.add_role "nodejs"
    chef.add_role "redis"
    chef.add_role "postgresql"
    chef.add_role "rbenv"

    chef.environments_path = "environments"
    chef.environment = "development"
    chef.data_bags_path = "data_bags"
  end

end
